//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newmoi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_HANG
    {
        public int DAT_HANG_ID { get; set; }
        public Nullable<int> KHACH_HANG_ID { get; set; }
        public Nullable<System.DateTime> NGAY_DAT { get; set; }
        public decimal TONG_TIEN { get; set; }
        public string TRANG_THAI { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
