//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newmoi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.DAT_HANG = new HashSet<DAT_HANG>();
        }
    
        public int KHACH_HANG_ID { get; set; }
        public string HO_TEN { get; set; }
        public string EMAIL { get; set; }
        public string SODIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAY_DANG_KY { get; set; }
        public string MAT_KHAU { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_HANG> DAT_HANG { get; set; }
    }
}
