//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k22cnt3_tavanthang_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_HOAT_DONG
    {
        public int LOG_ID { get; set; }
        public Nullable<int> QUAN_TRI_ID { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<System.DateTime> THOI_GIAN { get; set; }
    
        public virtual QUAN_TRI_VIEN QUAN_TRI_VIEN { get; set; }
    }
}
