//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newmoi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUAN_TRI_VIEN()
        {
            this.LOG_HOAT_DONG = new HashSet<LOG_HOAT_DONG>();
        }
    
        public int QUAN_TRI_ID { get; set; }
        public string HO_TEN { get; set; }
        public string EMAIL { get; set; }
        public string MAT_KHAU { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_HOAT_DONG> LOG_HOAT_DONG { get; set; }
    }
}
