//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newmoi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        public int SAN_PHAM_ID { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public string MO_TA { get; set; }
        public decimal GIA { get; set; }
        public int SO_LUONG { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
        public Nullable<int> CHIEN_DICH_ID { get; set; }
    
        public virtual CHIEN_DICH CHIEN_DICH { get; set; }
    }
}
